name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySimpleGUI==4.60.0 pyinstaller
      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --icon=favicon.ico batch_kml_styler.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: kml-styler-windows
          path: dist/batch_kml_styler.exe
