# .github/workflows/build-win.yml
name: Сборка Windows EXE

# Триггер при пуше в main
on:
  push:
    branches: [ main ]

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install PySimpleGUI==4.60.0 pyinstaller

      - name: Собрать EXE
        run: |
          pyinstaller --onefile --windowed --icon=favicon.ico batch_kml_styler.py

      - name: Загрузить артефакт
        uses: actions/upload-artifact@v4
        with:
          name: kml-styler-windows
          path: dist/batch_kml_styler.exe
